#ifndef _CONVLAYERIP_L3_H_
#define _CONVLAYERIP_L3_H_

#include "Datatype.h"


// top level function for HW synthesis
void Conv_L3(IMAGE_DATA_TYPE ImgIn[AVGP_HEIGHT][AVGP_WIDTH], IMAGE_DATA_TYPE ConvOutput[L3_MAX_OUTPUT_HEIGHT][L3_MAX_OUTPUT_WIDTH], IMAGE_DATA_TYPE ConvMapData_r[CONVLENGTH][CONVLENGTH]);
void L3_addmat(IMAGE_DATA_TYPE ImgIn[L3_MAX_OUTPUT_HEIGHT][L3_MAX_OUTPUT_WIDTH], IMAGE_DATA_TYPE ImgAdd[L3_MAX_OUTPUT_HEIGHT][L3_MAX_OUTPUT_WIDTH]);
void rotationConv_L3(IMAGE_DATA_TYPE ConvMapData_r[CONVLENGTH][CONVLENGTH], IMAGE_DATA_TYPE ConvMapData[CONVLENGTH][CONVLENGTH]);
#endif